site_name: mlr - a lightweight Python package for linear regression based statistical modeling
nav:
    - Home: index.md
    - Starter examples: starter-examples.md
    - Methods: methods.md
site_author: Tirthajyoti Sarkar
repo_url: https://github.com/tirthajyoti/mlr/
